gis_folder = "gis_clean" #dossier où sont rangés les shapefiles des DRZ
shapefile_paris = gis_folder+"\\paris.shp" #adresse de la shapefile de paris (utilisé seulement comme référence de crs)
drz_composition_path = "python_files\\get_data\\existing_insees.txt" #pas besoin de modifier
ms_folder = "MS_&_ATT_clean\\MS" #dossier ou sont rangés les modal shares
att_folder = "MS_&_ATT_clean\\ATT" #dossier où sont rangés les average travel time
er_folder = "ER_clean" #dossier où sont rnagés les émissions
skip_insees = [100092,100083,100074,100065,100014,100028,100042,100056] #insees pour lesquelles on ne veut pas calculer les datas (par exemple les départements entiers car c'est des outliers)
csv_data_communes_path = "python_files\\get_data\\data_communes.csv" #adresse ou les caractéristiques des communes seront stockées
file_coeff = "python_files\\get_data\\coeff_join.json" #adresse où sont stockés les coeff de jointure de chaque drz
dest_folder_pc = "python_files\\petite_couronne\\" #dossier contenant des tracés de la petite couronne
file_mat_ext = "python_files\\get_data\\mat_extended.json" #adresse matrice adjacence étendue
file_mat = "python_files\\get_data\\mat.json" #adresse matrice d'adjacence 
network_file = "python_files\\output_5pc\\output_file.shp" #doit poiter vers un réseau routier existant
communes_idf_file = "python_files\\communes-dile-de-france-au-01-janvier\\communes-dile-de-france-au-01-janvier.shp" #tracé des communes d'île-de-france
