gis_folder = "gis_clean"
shapefile_paris = gis_folder+"\\paris.shp"
drz_composition_path = "python_files\\get_data\\existing_insees.txt"
ms_folder = "MS_&_ATT_clean\\MS"
att_folder = "MS_&_ATT_clean\\ATT"
er_folder = "ER_clean"